# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cf9902f5fb222e09085c4397a05423a9ff21aa46873a734e29b94130b73574de6c007d95e283768db2e64ac639e1c0b0c7a064102eb36296ab1ff0a9b159ec3

test:
  secret_key_base: a1e8721c1eb6e0a0f4277ac4d5d939df198b6d347859cfe547e00bad32f57a87541f2fbcb966c2b01cf93d3e13cf3ed9573a15387f6285483442c572e00b027e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
